---
title: "課?<a0>?練習模<e7><89><88>"
author: "yunyun"
date: "2020-10-14"
output: output_format
params:
  id: "410973113"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
"\u0928\u092e\u0938\u094d\u0924\u0947 \u0926\u0941\u0928\u093f\u092f\u093e"
```
```{r}
num <- c(1.5, 2, 3)
int <- c(1L, 3L, -2L)
char <- c("1.5","2","3")
logi <- c(T,T,F)

typeof(num)
typeof(int)
typeof(char)
typeof(logi)
```
```{r}
class(num)
class(int)
class(char)
class(logi)
```

```{r}
factor(
  字串向量
)
```
```{r}
ymd_hms(
  字串向量
)
```
##factor
```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```

```{r}
#10位學生的主系
majors10_factor <- 
  factor(
    c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)
# 或
majors10_factor <- factor(
  c(majors10_char)
)

typeof(majors10_factor)
class(majors10_factor)

```

```{r}
"1"+"1.5"
1+1.5
```

```{r}
class("1")
class("1.5")
```
##-------------------------------------------- #這叫分隔線
```{r}
as.numeric("1")
```
```{r haha}
a<- "1" #a被字串取代  #字串:" "
as.numeric(a)->a #a變成數字了,所以要再變回a
a+4
```

```{r}
a<- "1"
a<-1 #a變成數字1,所以不用再變回a
as.numeric(a) 
a+4
```
```{r}
majors10_char
majors10_factor
```
```{r}
as.integer(majors10_factor) 
```
```{r}
as.integer(majors10_char) 
```
```{r}
a<-factor(c("一","二","三"))
a
```

