---
title: "課?<a0>?練習模<e7><89><88>"
author: "yunyun"
date: "2020-11-20"
output: output_format
params:
  id: "410973113"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
vectorExample <- c("小明","小英","大雄")

# 有多少位置可選：
length(vectorExample)

#--------------------------------

listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)





  `.台北市預報元素值` <- 
  list(
    city="台北市",
    high=25,
    low=18
  )
`.新北市預報元素值` <- 
  list(
    city="新北市",
    high=24,
    low=15
  )

library(lubridate)
`今明天氣` <-
  list(
    `今天日期`=ymd("2020-03-31"),
    `明天天氣`=ymd("2020-04-01"),
    `各地預報`=list(
      `.台北市預報元素值`,
      `.新北市預報元素值`
      )

  )
```

```{r}
# 有多少名字可選：
names(listExample)

listExample$student
listExample$`學期` # 特殊命名依然要用反頓點呼叫
```

```{r}
listExample[["student"]]
listExample$student

listExample[["學期"]] # 小心不是反頓點喔。
listExample$`學期`
```

```{r}
vectorExample
vectorExample[c(1,3)]
```

```{r}
# 顯示到第一層
str(listExample, max.level=1) #跑出來的List of  2是list裡面的長度，例如:list(A,B,C)共有三個東東，也就是list of 3，這裡的list of 2分別為`108-1`和`108-2`。

listExample[c(1,2)]
```

